server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
#          uri: file://C:/git-local-repo
          uri: https://github.com/doha23/spring-cloud-config
#          username: doha23
#          password: [password]